---
- include: facts.yml

- include: syncoid_packages.yml
  when:
    - inventory_hostname in groups['syncoid']

- include: syncoid_crons.yml
  when:
    - inventory_hostname in groups['syncoid']

- include: syncoid_directories.yml
  when:
    - inventory_hostname in groups['syncoid']

- include: syncoid_users.yml
  when:
    - inventory_hostname in groups['sanoid']
    - hostvars[inventory_hostname].syncoid_master

- include: sanoid_packages.yml
  when:
    - inventory_hostname in groups['sanoid']

- include: sanoid_crons.yml

- include: sanoid_directories.yml
  when:
    - inventory_hostname in groups['sanoid']
