---
- name: Kill All Sanoid Process
  shell: killall sanoid || true
  args:
    warn: false

- name: Uninstall Sanoid Binary
  file:
    path: /usr/local/bin/sanoid
    state: absent

- name: Uninstall Sanoid Cron Binary
  file:
    path: /usr/local/bin/sanoid-cron
    state: absent
