---
- name: Kill All Syncoid Process
  shell: killall syncoid || true
  args:
    warn: false

- name: Uninstall Syncoid Binary
  file:
    path: /usr/local/bin/syncoid
    state: absent

- name: Uninstall Syncoid Cron Binary
  file:
    path: /usr/local/bin/syncoid-cron
    state: absent
