---
- name: Generate Sanoid Configuration
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: 0644

- name: Create Sanoid Log
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 0644
  with_items:
    - /var/log/sanoid-cron.log

- name: Add Sanoid Log to be Rotated
  blockinfile:
    path: /etc/logrotate.d/sanoid
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      /var/log/sanoid-cron.log {
        create 0644 root root
        rotate 14
        daily
        compress
        missingok
        notifempty
      }
