---
- name: Configure Sanoid Cron Job
  cron:
    name: sanoid-cron
    job: /usr/local/bin/sanoid-cron
    minute: "{{ sanoid_cron_minutes }}"
    hour: "{{ sanoid_cron_hours }}"
    user: root
    state: present
