---
- name: Install Required Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - curl
    - wget
    - rsync
    - logrotate
    - libcapture-tiny-perl
